LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := FirefoxLite
LOCAL_MODULE_TAGS := optional 
LOCAL_SRC_FILES := FirefoxLite_v2.1.13_19177.apk
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_OVERRIDES_PACKAGES := Browser
LOCAL_PRODUCT_MODULE := true
include $(BUILD_PREBUILT)
